export const operatorFormConstants = {
  OPERATORS_LIST_LOADED_SUCCESS: 'OPERATORS_LIST_LOADED_SUCCESS',
  OPERATORS_LIST_LOADED_FAILURE: 'OPERATORS_LIST_LOADED_FAILURE',
  OPERATORS_LIST_LOADING: 'OPERATORS_LIST_LOADING',
  OPERATOR_SELECTED: 'OPERATOR_SELECTED'
};