export const paymentFormConstants = {
  PAYMENT_FORM_SUBMITTED_SUCCESS: 'PAYMENT_FORM_SUBMITTED_SUCCESS',
  PAYMENT_FORM_SUBMITTED_FAILURE: 'PAYMENT_FORM_SUBMITTED_FAILURE',
  PAYMENT_FORM_SUBMITTED_LOADING: 'PAYMENT_FORM_SUBMITTED_LOADING',
  PAYMENT_FORM_DATA_CLEAR: 'PAYMENT_FORM_DATA_CLEAR',
  PAYMENT_FORM_ERROR_MESSAGE_CLOSE: 'PAYMENT_FORM_ERROR_MESSAGE_CLOSE'
};